<a href="https://colab.research.google.com/github/nickmendoza224/164-project/blob/main/164.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
!pip install sqlalchemy psycopg2-binary -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 44.6 MB/s eta 0:00:00

In [9]:
from sqlalchemy import create_engine
import pandas as pd

DATABASE_URL = "postgresql://neondb_owner:npg_PuYM28eKCWax@ep-fancy-bonus-ak0nv59r-pooler.c-3.us-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

engine = create_engine(DATABASE_URL)

pd.read_sql("SELECT version();", engine)

                                             version
0  PostgreSQL 17.8 (130b160) on aarch64-unknown-l...

In [23]:
from google.colab import files
import zipfile
import os
import glob

# Upload csv.zip and hops.zip
uploaded = files.upload()

# Create folder for extracted files
os.makedirs("uploaded_data", exist_ok=True)

# Extract all zip files
for filename in uploaded.keys():
    print("Uploaded:", filename)

    if filename.endswith(".zip"):
        with zipfile.ZipFile(filename, "r") as zip_ref:
            zip_ref.extractall("uploaded_data")
            print("Extracted:", filename)

# Show extracted files
print("\nExtracted files:")
for path in glob.glob("uploaded_data/**/*", recursive=True):
    print(path)

KeyboardInterrupt:

In [13]:
#creating Data Frame
import pandas as pd
import os
import re
import glob

# Find all CSV files extracted from csv.zip
csv_files = glob.glob("uploaded_data/**/*.csv", recursive=True)

print("CSV files found:", len(csv_files))
for f in csv_files:
    print(f)

if len(csv_files) == 0:
    raise ValueError("No CSV files found. Make sure csv.zip was uploaded and extracted.")

all_dfs = []

for file in csv_files:
    temp = pd.read_csv(file, sep=None, engine="python")

    base = os.path.basename(file)

    # Extract timestamp from filename
    match = re.search(r"(\d{4}-\d{2}-\d{2}_\d{2}-\d{2}-\d{2})", base)
    run_timestamp = match.group(1) if match else base

    temp["source_file"] = base
    temp["run_id"] = "run_" + run_timestamp

    all_dfs.append(temp)

df = pd.concat(all_dfs, ignore_index=True)

print("Total DNS packet rows loaded:", len(df))
print("Number of runs loaded:", df["run_id"].nunique())
print("Columns:")
print(df.columns.tolist())

df.head()

CSV files found: 11
uploaded_data/csv/dns_capture_2026-04-26_20-40-45.csv
uploaded_data/csv/dns_capture_2026-04-26_15-36-16.csv
uploaded_data/csv/dns_capture_2026-04-26_20-55-15.csv
uploaded_data/csv/dns_capture_2026-04-26_20-45-56.csv
uploaded_data/csv/dns_capture_2026-04-26_20-43-20.csv
uploaded_data/csv/dns_capture_2026-04-26_20-52-37.csv
uploaded_data/csv/dns_capture_2026-04-26_20-57-49.csv
uploaded_data/csv/dns_capture_2026-04-26_20-35-24.csv
uploaded_data/csv/dns_capture_2026-04-26_20-29-47.csv
uploaded_data/csv/dns_capture_2026-04-26_20-32-47.csv
uploaded_data/csv/dns_capture_2026-04-26_20-49-12.csv
Total DNS packet rows loaded: 6396
Number of runs loaded: 11
Columns:
['frame.number', 'frame.time', 'ip.src', 'ip.dst', 'ipv6.src', 'ipv6.dst', 'udp.srcport', 'udp.dstport', 'tcp.srcport', 'tcp.dstport', 'dns.flags.response', 'dns.qry.name', 'dns.qry.type', 'dns.resp.type', 'dns.flags.rcode', 'dns.time', 'dns.a', 'dns.aaaa', 'frame.len', 'udp.length', 'tcp.len', 'source_file', 'run_id']

,frame.number,frame.time,ip.src,ip.dst,ipv6.src,ipv6.dst,udp.srcport,udp.dstport,tcp.srcport,tcp.dstport,...,dns.resp.type,dns.flags.rcode,dns.time,dns.a,dns.aaaa,frame.len,udp.length,tcp.len,source_file,run_id
0,1,"Apr 26, 2026 20:40:47.923821000 PDT",127.0.0.1,127.0.0.1,NaN,NaN,50353,5300,NaN,NaN,...,41,NaN,NaN,NaN,NaN,96,60,NaN,dns_capture_2026-04-26_20-40-45.csv,run_2026-04-26_20-40-45
1,2,"Apr 26, 2026 20:40:47.923951000 PDT",172.21.0.1,172.21.0.2,NaN,NaN,40272,53,NaN,NaN,...,41,NaN,NaN,NaN,NaN,96,60,NaN,dns_capture_2026-04-26_20-40-45.csv,run_2026-04-26_20-40-45
2,3,"Apr 26, 2026 20:40:47.923957000 PDT",172.21.0.1,172.21.0.2,NaN,NaN,40272,53,NaN,NaN,...,41,NaN,NaN,NaN,NaN,96,60,NaN,dns_capture_2026-04-26_20-40-45.csv,run_2026-04-26_20-40-45
3,4,"Apr 26, 2026 20:40:47.924257000 PDT",172.21.0.2,172.21.0.1,NaN,NaN,53,40272,NaN,NaN,...,"1,41",0.0,0.000306,142.251.214.46,NaN,106,70,NaN,dns_capture_2026-04-26_20-40-45.csv,run_2026-04-26_20-40-45
4,5,"Apr 26, 2026 20:40:47.924263000 PDT",172.21.0.2,172.21.0.1,NaN,NaN,53,40272,NaN,NaN,...,"1,41",0.0,NaN,142.251.214.46,NaN,106,70,NaN,dns_capture_2026-04-26_20-40-45.csv,run_2026-04-26_20-40-45

Warning: Total number of columns (23) exceeds max_columns (20) limiting to first (20) columns.

In [14]:
from datetime import datetime
import pandas as pd
import numpy as np

# ==============================
# Clean DNS Packet Data
# ==============================

# Clean column names for Postgres
df.columns = (
     df.columns
    .str.strip()
    .str.lower()
    .str.replace(".", "_", regex=False)
    .str.replace(" ", "_", regex=False)
    .str.replace("-", "_", regex=False)
)

# Expected columns from tshark + loader
expected_cols = [
    "frame_number", "frame_time", "ip_src", "ip_dst",
    "ipv6_src", "ipv6_dst",
    "udp_srcport", "udp_dstport",
    "tcp_srcport", "tcp_dstport",
    "dns_flags_response",
    "dns_qry_name", "dns_qry_type",
    "dns_resp_type", "dns_flags_rcode",
    "dns_time", "dns_a", "dns_aaaa",
    "frame_len", "udp_length", "tcp_len",
    "source_file", "run_id"
]

# Add missing columns just in case
for col in expected_cols:
    if col not in df.columns:
        df[col] = None

# If run_id was not created during loading, create one from source_file
if df["run_id"].isna().all():
    df["run_id"] = df["source_file"].astype(str).str.extract(
        r"(\d{4}_\d{2}_\d{2}_\d{2}_\d{2}_\d{2}|\d{4}-\d{2}-\d{2}_\d{2}-\d{2}-\d{2})"
    )[0]
    df["run_id"] = "run_" + df["run_id"].fillna(datetime.now().strftime("%Y-%m-%d_%H-%M-%S"))

# Convert numeric fields
numeric_cols = [
    "frame_number", "udp_srcport", "udp_dstport",
    "tcp_srcport", "tcp_dstport",
    "dns_flags_response",
    "dns_qry_type", "dns_resp_type",
    "dns_flags_rcode",
    "dns_time", "frame_len", "udp_length", "tcp_len"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Convert timestamp
df["frame_time_clean"] = pd.to_datetime(df["frame_time"], errors="coerce")

# Clean domain names
df["dns_qry_name"] = (
    df["dns_qry_name"]
    .fillna("")
    .astype(str)
    .str.strip()
    .str.lower()
    .str.rstrip(".")
)

# Clean DNS answer fields
df["dns_a"] = df["dns_a"].fillna("").astype(str).str.strip()
df["dns_aaaa"] = df["dns_aaaa"].fillna("").astype(str).str.strip()

# Query/response flags
df["is_response"] = df["dns_flags_response"] == 1
df["is_query"] = df["dns_flags_response"] == 0

# Blocked domain detection
# Pi-hole commonly returns 0.0.0.0 for blocked IPv4 domains
df["blocked"] = df["dns_a"].str.contains("0.0.0.0", regex=False)

# DNS response code labels
rcode_map = {
    0: "NOERROR",
    1: "FORMERR",
    2: "SERVFAIL",
    3: "NXDOMAIN",
    4: "NOTIMP",
    5: "REFUSED"
}

df["rcode_label"] = df["dns_flags_rcode"].map(rcode_map).fillna("UNKNOWN")

# DNS query type labels
query_type_map = {
    1: "A",
    2: "NS",
    5: "CNAME",
    12: "PTR",
    15: "MX",
    28: "AAAA",
    41: "OPT",
    65: "HTTPS"
}

df["query_type_label"] = df["dns_qry_type"].map(query_type_map).fillna("OTHER")

# Classify traffic path
def classify_path(row):
    src = str(row.get("ip_src", ""))
    dst = str(row.get("ip_dst", ""))
    udp_src = row.get("udp_srcport")
    udp_dst = row.get("udp_dstport")
    tcp_src = row.get("tcp_srcport")
    tcp_dst = row.get("tcp_dstport")

    if udp_src == 5300 or udp_dst == 5300 or tcp_src == 5300 or tcp_dst == 5300:
        return "localhost_to_pihole_port_5300"

    elif src.startswith("172.21.") or dst.startswith("172.21."):
        return "docker_bridge"

    elif src in ["8.8.8.8", "8.8.4.4", "1.1.1.1"] or dst in ["8.8.8.8", "8.8.4.4", "1.1.1.1"]:
        return "upstream_dns_resolver"

    elif src.startswith("127.") or dst.startswith("127."):
        return "localhost_or_system_resolver"

    else:
        return "other"

df["resolver_path"] = df.apply(classify_path, axis=1)

# Helpful derived fields
df["has_dns_query_name"] = df["dns_qry_name"] != ""
df["has_dns_answer"] = df["dns_a"] != ""

df["packet_direction"] = np.where(
    df["is_query"],
    "query",
    np.where(df["is_response"], "response", "unknown")
)

# Reorder important columns first
preferred_order = [
    "run_id", "source_file",
    "frame_number", "frame_time", "frame_time_clean",
    "ip_src", "ip_dst",
    "udp_srcport", "udp_dstport",
    "tcp_srcport", "tcp_dstport",
    "packet_direction",
    "dns_qry_name", "query_type_label",
    "dns_a", "dns_aaaa",
    "blocked",
    "dns_time",
    "rcode_label",
    "frame_len", "udp_length", "tcp_len",
    "resolver_path"
]

remaining_cols = [col for col in df.columns if col not in preferred_order]
df = df[preferred_order + remaining_cols]

print("Prepared rows:", len(df))
print("Number of runs:", df["run_id"].nunique())
print("\nRows per run:")
print(df["run_id"].value_counts().sort_index())

print("\nResolver paths:")
print(df["resolver_path"].value_counts())

df.head()

Prepared rows: 6396
Number of runs: 11

Rows per run:
run_id
run_2026-04-26_15-36-16    536
run_2026-04-26_20-29-47    675
run_2026-04-26_20-32-47    540
run_2026-04-26_20-35-24    570
run_2026-04-26_20-40-45    603
run_2026-04-26_20-43-20    565
run_2026-04-26_20-45-56    561
run_2026-04-26_20-49-12    631
run_2026-04-26_20-52-37    613
run_2026-04-26_20-55-15    532
run_2026-04-26_20-57-49    570
Name: count, dtype: int64

Resolver paths:
resolver_path
upstream_dns_resolver            3725
localhost_or_system_resolver     1523
docker_bridge                     884
localhost_to_pihole_port_5300     264
Name: count, dtype: int64

/tmp/ipykernel_9212/2231293086.py:59: FutureWarning: Parsed string "Apr 26, 2026 20:40:47.923821000 PDT" included an un-recognized timezone "PDT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["frame_time_clean"] = pd.to_datetime(df["frame_time"], errors="coerce")

,run_id,source_file,frame_number,frame_time,frame_time_clean,ip_src,ip_dst,udp_srcport,udp_dstport,tcp_srcport,...,ipv6_src,ipv6_dst,dns_flags_response,dns_qry_type,dns_resp_type,dns_flags_rcode,is_response,is_query,has_dns_query_name,has_dns_answer
0,run_2026-04-26_20-40-45,dns_capture_2026-04-26_20-40-45.csv,1,"Apr 26, 2026 20:40:47.923821000 PDT",2026-04-26 20:40:47.923821,127.0.0.1,127.0.0.1,50353,5300,NaN,...,NaN,NaN,0,1,41.0,NaN,False,True,True,False
1,run_2026-04-26_20-40-45,dns_capture_2026-04-26_20-40-45.csv,2,"Apr 26, 2026 20:40:47.923951000 PDT",2026-04-26 20:40:47.923951,172.21.0.1,172.21.0.2,40272,53,NaN,...,NaN,NaN,0,1,41.0,NaN,False,True,True,False
2,run_2026-04-26_20-40-45,dns_capture_2026-04-26_20-40-45.csv,3,"Apr 26, 2026 20:40:47.923957000 PDT",2026-04-26 20:40:47.923957,172.21.0.1,172.21.0.2,40272,53,NaN,...,NaN,NaN,0,1,41.0,NaN,False,True,True,False
3,run_2026-04-26_20-40-45,dns_capture_2026-04-26_20-40-45.csv,4,"Apr 26, 2026 20:40:47.924257000 PDT",2026-04-26 20:40:47.924257,172.21.0.2,172.21.0.1,53,40272,NaN,...,NaN,NaN,1,1,NaN,0.0,True,False,True,True
4,run_2026-04-26_20-40-45,dns_capture_2026-04-26_20-40-45.csv,5,"Apr 26, 2026 20:40:47.924263000 PDT",2026-04-26 20:40:47.924263,172.21.0.2,172.21.0.1,53,40272,NaN,...,NaN,NaN,1,1,NaN,0.0,True,False,True,True

In [15]:
df["resolver_path"].value_counts()

resolver_path
upstream_dns_resolver            3725
localhost_or_system_resolver     1523
docker_bridge                     884
localhost_to_pihole_port_5300     264
Name: count, dtype: int64

In [16]:
df[["frame_number", "ip_src", "ip_dst", "udp_srcport", "udp_dstport", "dns_qry_name", "dns_a", "blocked", "dns_time", "resolver_path"]].head(30)

,frame_number,ip_src,ip_dst,udp_srcport,udp_dstport,dns_qry_name,dns_a,blocked,dns_time,resolver_path
0,1,127.0.0.1,127.0.0.1,50353,5300,youtube.com,,False,NaN,localhost_to_pihole_port_5300
1,2,172.21.0.1,172.21.0.2,40272,53,youtube.com,,False,NaN,docker_bridge
2,3,172.21.0.1,172.21.0.2,40272,53,youtube.com,,False,NaN,docker_bridge
3,4,172.21.0.2,172.21.0.1,53,40272,youtube.com,142.251.214.46,False,0.000306,docker_bridge
4,5,172.21.0.2,172.21.0.1,53,40272,youtube.com,142.251.214.46,False,NaN,docker_bridge
5,6,172.21.0.2,8.8.8.8,49036,53,youtube.com,,False,NaN,docker_bridge
6,7,172.21.0.2,8.8.8.8,49036,53,youtube.com,,False,NaN,docker_bridge
7,8,192.168.1.156,8.8.8.8,49036,53,youtube.com,,False,NaN,upstream_dns_resolver
8,9,127.0.0.1,127.0.0.1,5300,50353,youtube.com,142.251.214.46,False,0.000582,localhost_to_pihole_port_5300
9,10,172.21.0.2,8.8.4.4,49036,53,youtube.com,,False,NaN,docker_bridge
10,11,172.21.0.2,8.8.4.4,49036,53,youtube.com,,False,NaN,docker_bridge
11,12,192.168.1.156,8.8.4.4,49036,53,youtube.com,,False,NaN,upstream_dns_resolver
12,13,8.8.4.4,192.168.1.156,53,49036,youtube.com,142.251.214.46,False,0.032515,upstream_dns_resolver
13,14,8.8.4.4,172.21.0.2,53,49036,youtube.com,142.251.214.46,False,0.032549,docker_bridge
14,15,8.8.4.4,172.21.0.2,53,49036,youtube.com,142.251.214.46,False,NaN,docker_bridge
15,16,8.8.8.8,192.168.1.156,53,49036,youtube.com,142.251.214.46,False,0.038058,upstream_dns_resolver
16,17,8.8.8.8,172.21.0.2,53,49036,youtube.com,142.251.214.46,False,0.038094,docker_bridge
17,18,8.8.8.8,172.21.0.2,53,49036,youtube.com,142.251.214.46,False,NaN,docker_bridge
18,19,127.0.0.1,127.0.0.1,53523,5300,google.com,,False,NaN,localhost_to_pihole_port_5300
19,20,172.21.0.1,172.21.0.2,47911,53,google.com,,False,NaN,docker_bridge
20,21,172.21.0.1,172.21.0.2,47911,53,google.com,,False,NaN,docker_bridge
21,22,172.21.0.2,172.21.0.1,53,47911,google.com,142.251.218.110,False,0.000313,docker_bridge
22,23,172.21.0.2,172.21.0.1,53,47911,google.com,142.251.218.110,False,NaN,docker_bridge
23,24,172.21.0.2,8.8.4.4,49265,53,google.com,,False,NaN,docker_bridge
24,25,172.21.0.2,8.8.4.4,49265,53,google.com,,False,NaN,docker_bridge
25,26,192.168.1.156,8.8.4.4,49265,53,google.com,,False,NaN,upstream_dns_resolver
26,27,127.0.0.1,127.0.0.1,5300,53523,google.com,142.251.218.110,False,0.000967,localhost_to_pihole_port_5300
27,28,8.8.4.4,192.168.1.156,53,49265,google.com,172.217.12.110,False,0.032674,upstream_dns_resolver
28,29,8.8.4.4,172.21.0.2,53,49265,google.com,172.217.12.110,False,0.032708,docker_bridge
29,30,8.8.4.4,172.21.0.2,53,49265,google.com,172.217.12.110,False,NaN,docker_bridge

In [17]:
test_domains = [
    "youtube.com",
    "google.com",
    "facebook.com",
    "reddit.com",
    "amazon.com",
    "netflix.com",
    "twitter.com",
    "instagram.com",
    "yahoo.com",
    "wikipedia.org",
    "doubleclick.net",
    "ads.google.com"
]

pihole_responses = df[
    (df["is_response"] == True) &
    (df["dns_qry_name"].isin(test_domains)) &
    (df["resolver_path"].isin([
        "localhost_to_pihole_port_5300",
        "docker_bridge"
    ]))
].copy()

pihole_responses[
    [
        "frame_time_clean",
        "dns_qry_name",
        "dns_a",
        "blocked",
        "dns_time",
        "frame_len",
        "resolver_path"
    ]
].head(30)

,frame_time_clean,dns_qry_name,dns_a,blocked,dns_time,frame_len,resolver_path
3,2026-04-26 20:40:47.924257,youtube.com,142.251.214.46,False,0.000306,106,docker_bridge
4,2026-04-26 20:40:47.924263,youtube.com,142.251.214.46,False,NaN,106,docker_bridge
8,2026-04-26 20:40:47.924403,youtube.com,142.251.214.46,False,0.000582,106,localhost_to_pihole_port_5300
13,2026-04-26 20:40:47.957068,youtube.com,142.251.214.46,False,0.032549,100,docker_bridge
14,2026-04-26 20:40:47.957074,youtube.com,142.251.214.46,False,NaN,100,docker_bridge
16,2026-04-26 20:40:47.962473,youtube.com,142.251.214.46,False,0.038094,100,docker_bridge
17,2026-04-26 20:40:47.962478,youtube.com,142.251.214.46,False,NaN,100,docker_bridge
21,2026-04-26 20:40:48.945463,google.com,142.251.218.110,False,0.000313,105,docker_bridge
22,2026-04-26 20:40:48.945468,google.com,142.251.218.110,False,NaN,105,docker_bridge
26,2026-04-26 20:40:48.946012,google.com,142.251.218.110,False,0.000967,105,localhost_to_pihole_port_5300
28,2026-04-26 20:40:48.978264,google.com,172.217.12.110,False,0.032708,99,docker_bridge
29,2026-04-26 20:40:48.978268,google.com,172.217.12.110,False,NaN,99,docker_bridge
33,2026-04-26 20:40:49.968813,facebook.com,57.144.202.1,False,0.000257,107,docker_bridge
34,2026-04-26 20:40:49.968819,facebook.com,57.144.202.1,False,NaN,107,docker_bridge
38,2026-04-26 20:40:49.969367,facebook.com,57.144.202.1,False,0.001095,107,localhost_to_pihole_port_5300
40,2026-04-26 20:40:50.002210,facebook.com,57.144.202.1,False,0.033186,101,docker_bridge
41,2026-04-26 20:40:50.002214,facebook.com,57.144.202.1,False,NaN,101,docker_bridge
60,2026-04-26 20:40:51.003597,reddit.com,"151.101.1.140,151.101.129.140,151.101.65.140,1...",False,0.000492,153,docker_bridge
61,2026-04-26 20:40:51.003606,reddit.com,"151.101.1.140,151.101.129.140,151.101.65.140,1...",False,NaN,153,docker_bridge
62,2026-04-26 20:40:51.003809,reddit.com,"151.101.1.140,151.101.129.140,151.101.65.140,1...",False,0.000958,153,localhost_to_pihole_port_5300
67,2026-04-26 20:40:51.020754,reddit.com,"151.101.129.140,151.101.1.140,151.101.65.140,1...",False,0.016933,147,docker_bridge
68,2026-04-26 20:40:51.020758,reddit.com,"151.101.129.140,151.101.1.140,151.101.65.140,1...",False,NaN,147,docker_bridge
72,2026-04-26 20:40:52.040500,amazon.com,"98.82.161.185,98.87.170.71,98.87.170.74",False,0.000308,131,docker_bridge
73,2026-04-26 20:40:52.040506,amazon.com,"98.82.161.185,98.87.170.71,98.87.170.74",False,NaN,131,docker_bridge
74,2026-04-26 20:40:52.040748,amazon.com,"98.82.161.185,98.87.170.71,98.87.170.74",False,0.001005,131,localhost_to_pihole_port_5300
78,2026-04-26 20:40:53.069148,netflix.com,"44.234.232.238,44.237.234.25,44.242.60.85",False,0.000253,138,docker_bridge
79,2026-04-26 20:40:53.069152,netflix.com,"44.234.232.238,44.237.234.25,44.242.60.85",False,NaN,138,docker_bridge
83,2026-04-26 20:40:53.069675,netflix.com,"44.234.232.238,44.237.234.25,44.242.60.85",False,0.000886,138,localhost_to_pihole_port_5300
85,2026-04-26 20:40:53.104099,netflix.com,"44.234.232.238,44.242.60.85,44.237.234.25",False,0.034901,132,docker_bridge
86,2026-04-26 20:40:53.104104,netflix.com,"44.234.232.238,44.242.60.85,44.237.234.25",False,NaN,132,docker_bridge

In [22]:
pd.read_sql("""
SELECT run_id,
       COUNT(*) AS packet_rows
FROM dns_packet_captures
GROUP BY run_id
ORDER BY run_id DESC
LIMIT 10;
""", engine)

                    run_id  packet_rows
0  run_2026-04-26_20-57-49          570
1  run_2026-04-26_20-55-15          532
2  run_2026-04-26_20-52-37          613
3  run_2026-04-26_20-49-12          631
4  run_2026-04-26_20-45-56          561
5  run_2026-04-26_20-43-20          565
6  run_2026-04-26_20-40-45          603
7  run_2026-04-26_20-35-24          570
8  run_2026-04-26_20-32-47          540
9  run_2026-04-26_20-29-47          675

Install packages
Connect to Neon
Upload CSV
Clean packet data
Inspect captured traffic
Create Pi-hole response dataset
Create summary table
Upload raw data to Neon
Upload summary to Neon
Verify upload

Testing to see if posssible to pull from Neon

In [25]:
packet_df = pd.read_sql("SELECT * FROM dns_packet_captures;", engine)
summary_df = pd.read_sql("SELECT * FROM dns_run_summary;", engine)

print(packet_df.shape)
print(summary_df.shape)

summary_df.head()

(6396, 33)
(12, 8)

,dns_qry_name,total_responses,blocked,avg_dns_time,avg_packet_size,min_packet_size,max_packet_size,answers
0,ads.google.com,33,True,0.000412,116.000000,116,116,0.0.0.0
1,amazon.com,43,False,0.004871,132.674419,131,137,"98.82.161.185,98.87.170.71,98.87.170.74, 98.82..."
2,doubleclick.net,33,True,0.000622,117.000000,117,117,0.0.0.0
3,facebook.com,55,False,0.016458,104.272727,101,107,57.144.202.1
4,google.com,49,False,0.009832,101.571429,99,105,"142.251.218.110, 142.251.218.142, 172.217.12.110"

In [37]:
print("model_df shape:", model_df.shape)
print("dns_summary shape:", dns_summary.shape)

print("\nmodel_df blocked counts:")
print(model_df["blocked"].value_counts())

print("\ndns_summary blocked counts:")
print(dns_summary["blocked"].astype(int).value_counts())

print("\nmodel_df columns:")
print(model_df.columns.tolist())

model_df shape: (132, 11)
dns_summary shape: (132, 11)

model_df blocked counts:
blocked
0    110
1     22
Name: count, dtype: int64

dns_summary blocked counts:
blocked
0    110
1     22
Name: count, dtype: int64

model_df columns:
['run_id', 'dns_qry_name', 'total_responses', 'blocked', 'avg_dns_time', 'min_dns_time', 'max_dns_time', 'avg_packet_size', 'min_packet_size', 'max_packet_size', 'answers']

In [38]:
dns_summary = (
    pihole_responses
    .groupby(["run_id", "dns_qry_name"])
    .agg(
        total_responses=("dns_qry_name", "count"),
        blocked=("blocked", "max"),
        avg_dns_time=("dns_time", "mean"),
        min_dns_time=("dns_time", "min"),
        max_dns_time=("dns_time", "max"),
        avg_packet_size=("frame_len", "mean"),
        min_packet_size=("frame_len", "min"),
        max_packet_size=("frame_len", "max"),
        answers=("dns_a", lambda x: ", ".join(sorted(set(x.dropna().astype(str)))))
    )
    .reset_index()
    .sort_values(["run_id", "dns_qry_name"])
)

model_df = dns_summary.copy()
model_df["blocked"] = model_df["blocked"].astype(bool).astype(int)

print("Rows:", len(model_df))
print("Runs:", model_df["run_id"].nunique())
print("Blocked counts:")
print(model_df["blocked"].value_counts())

dns_summary.head()

Rows: 132
Runs: 11
Blocked counts:
blocked
0    110
1     22
Name: count, dtype: int64

,run_id,dns_qry_name,total_responses,blocked,avg_dns_time,min_dns_time,max_dns_time,avg_packet_size,min_packet_size,max_packet_size,answers
0,run_2026-04-26_15-36-16,ads.google.com,3,True,0.000340,0.000193,0.000487,116.0,116,116,0.0.0.0
1,run_2026-04-26_15-36-16,amazon.com,5,False,0.005607,0.000250,0.015881,134.6,131,137,"98.82.161.185,98.87.170.74,98.87.170.71, 98.87..."
2,run_2026-04-26_15-36-16,doubleclick.net,3,True,0.000316,0.000168,0.000465,117.0,117,117,0.0.0.0
3,run_2026-04-26_15-36-16,facebook.com,5,False,0.011973,0.000337,0.034759,104.6,101,107,57.144.202.1
4,run_2026-04-26_15-36-16,google.com,5,False,0.008294,0.000218,0.024193,102.6,99,105,142.251.218.110

In [39]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
import pandas as pd

features = [
    "total_responses",
    "avg_dns_time",
    "avg_packet_size",
    "min_packet_size",
    "max_packet_size"
]

model_df = model_df.dropna(subset=features + ["blocked"])

X = model_df[features]
y = model_df["blocked"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42,
    stratify=y
)

models = {
    "Logistic Regression": Pipeline([
        ("scaler", StandardScaler()),
        ("model", LogisticRegression(max_iter=1000))
    ]),
    "KNN": Pipeline([
        ("scaler", StandardScaler()),
        ("model", KNeighborsClassifier())
    ]),
    "Random Forest": RandomForestClassifier(random_state=42)
}

results = []

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)

    results.append({
        "dataset": "dns_run_summary",
        "model": name,
        "accuracy": acc
    })

    print("=" * 50)
    print(name)
    print("Accuracy:", acc)
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))
    print("Classification Report:")
    print(classification_report(y_test, y_pred, zero_division=0))

results_df = pd.DataFrame(results)
results_df

==================================================
Logistic Regression
Accuracy: 0.8
Confusion Matrix:
[[27  6]
 [ 2  5]]
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.82      0.87        33
           1       0.45      0.71      0.56         7

    accuracy                           0.80        40
   macro avg       0.69      0.77      0.71        40
weighted avg       0.85      0.80      0.82        40

==================================================
KNN
Accuracy: 1.0
Confusion Matrix:
[[33  0]
 [ 0  7]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        33
           1       1.00      1.00      1.00         7

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40

==================================================
Random Forest
Accuracy: 1.0
Confusion Matrix:
[[33  0]
 [ 0  7]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        33
           1       1.00      1.00      1.00         7

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40

           dataset                model  accuracy
0  dns_run_summary  Logistic Regression       0.8
1  dns_run_summary                  KNN       1.0
2  dns_run_summary        Random Forest       1.0